### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by pbreah** [talyssonoc/react-laravel#33]
Excellent work, and appreciate you sharing it.

I'm new to React JS and recently familiar with Blade.

It would be great to have a full example on how to work with this component.

I have searched around the Web for examples using react-laravel, but since this is a fairly new subject specially with Laravel, it would be really helpful to have a full "Hello World" example using Laravel on how to implement this component step by step for creating an UI.

I'm clear on the installation, that is fine. But after reading the usage instructions, and I'm out of context on where or how to start implementing the blade helper:

@react_component(<componentName>[, props, options])

I have so many questions, that I believe only a full example can answer. It would be great to have an example using:
- How blade template files look like using this component.
- A before & after transformation from a regular blade view, to one that uses React with your component.
- A sample view with react components receiving data from Laravel.

I know this project is very recent, and appreciate you sharing this.

Thank you.

**Comment by talyssonoc** [comment]
Hey, glad you liked the project !

Actually, there's a example (I should put the link to it on README, I know :confused: ). The version and configuration is a little bit outdated, but since you already configured it it will be useful for you, since the view and component files are still up to date. Here it is: https://github.com/talyssonoc/react-laravel-example

Thanks !

**Comment by pbreah** [comment]
Thank you for your help. I'm starting to understand how this works.

Also wanted to let you know that the blade directive you have doesn't work for me using Lavavel 5.1.8 (LTS)

I did several tests using dd() and the Blade::extend() callback is never called. I'm using your latest commit: c1572d5704ce2f31c63b479f10f3b791a94bbe91

The only way this works is using: 

{!! React::render() !!}

Thanks

**Comment by talyssonoc** [comment]
Damn, it is working with some people, and not working with others :confused: , gotta find out why this is happening x_x

**Comment by tylervick** [comment]
I'm also getting this issue as well. Before I integrate this into my existing laravel project I'd like to see how this fully works.

**Comment by talyssonoc** [comment]
@pbreah and @tylerjvick Can you try this instructions here and say me if it does work? https://github.com/talyssonoc/react-laravel/issues/41#issuecomment-133704745

**Comment by carloct** [comment]
Hi, 

I think we see inconsistent behaviours because of:
1. the view cache layer, Blade actually compiles the views in plain PHP, if you extend/edit the compiler you need to recreate those views, try to clear the view cache `php artisan view:clear`after any change to the compiler.
2. I suspect the Blade::extend() syntax has changed, you can get around it using Blade::directive, and get rid of the matcher Example at http://laravel.com/docs/5.1/blade#extending-blade

**Comment by talyssonoc** [comment]
Hi, @carloct 

Does the `1` works for you? If so, I'm gonna put it on `README`!
About `2`, I didn't used `directive` because it is on the [docs for Laravel 5.0](http://laravel.com/docs/5.0/templates) and I wanted to keep it compatible with Laravel 5.x.

**Comment by talyssonoc** [comment]
@pbreah @tylerjvick can you check if @carloct 's answer work for you?

**Comment by carloct** [comment]
@talyssonoc 

1 worked for me, but I also changed it into a directive, so it might be both.

**Comment by talyssonoc** [comment]
Thanks, @carloct! Would you mind to change it back to `extend` just to test what of the solutions did it?

**Comment by linweili1201** [comment]
sorry for asking the stupid question, but i want to know how to run the example? do react views have any route url
