### ISSUE TITLE
V8Js::executeString():1: TypeError: Cannot call method 'renderToString' of undefined

### ISSUE THREAD

**Issue by kishanj918** [talyssonoc/react-laravel#59]
I am getting this error while using this package..

**Comment by TomCaserta** [comment]
This is because React now has ReactDOMServer. The React.renderToString method no longer exists. The react vendor files distributed with this package needs to be updated.

To get around this for now, download react.js and react-dom.js and react-dom-server.js, concatenate them together and in the config/react.php change the "source" to point to concatenated file.

See #49
